tap 'homebrew/bundle'
tap 'caskroom/cask'

cask_args appdir: "/Applications"

# Brewfile
brew 'git'
brew 'vim'
brew 'zsh'
brew 'cocoapods'
brew 'peco'
brew 'python'
brew 'tmux'
brew 'tree'

# cask
cask 'google-chrome'
cask 'slack'
cask 'github'
cask 'atom'

# vim: ft=conf
